*DECK CDATE
C
C
C
      CHARACTER*(*) FUNCTION CDATE(IDATE)
C
C RETURNS THE DATE IDATE AS AN INTEGER YYMMDD INTO THE CHARACTER STRING
C CDATE IN THE FORMAT YY/MM/DD.
C
      CHARACTER*8 BUFFER
C
C SPLIT IDATE INTO YY, MM AND DD.
C
      I=MOD(ABS(IDATE),1000000)
      IYR=I/10000
      I=I-IYR*10000
      IMN=I/100
      IDY=I-IMN*100
      WRITE (BUFFER,100) IYR,IMN,IDY
      CDATE = BUFFER
      RETURN
C
C FORMAT.
C
  100 FORMAT (SS,I2.2,'/',I2.2,'/',I2.2)
C
C END OF CHARACTER*8 FUNCTION CDATE.
C
      END
