*DECK CELGAL
C
C **************************************************************
      SUBROUTINE CELGAL ( ALPHA, DELTA, LONG, LAT )
C **************************************************************
C
C TRANSFORMS CELESTIAL COORDINATES (ALPHA,DELTA)
C INTO GALACTIC COORDINATES (LONG,LAT)
C ALPHA, DELTA, LONG, LAT IN DEGREES
C
      PARAMETER ( DEGRAD=3.1415926535/180.0
     &           ,RADDEG=1.0/DEGRAD )
      REAL LONG,LAT
C
      COS62  = COS(DEGRAD*62.6)
      SIN62  = SIN(DEGRAD*62.6)
      COSDEL = COS(DEGRAD*DELTA)
      SINDEL = SIN(DEGRAD*DELTA)
      SINALF = SIN(DEGRAD*(ALPHA-282.25))*COSDEL
      COSALF = COS(DEGRAD*(ALPHA-282.25))*COSDEL
      LAT    = RADDEG*ASIN(-SINALF*SIN62+SINDEL*COS62)
      LONG   = RADDEG*ATAN2((SINALF*COS62+SINDEL*SIN62),COSALF)+33.0
      IF ( LONG.LT.0 )  LONG = LONG+360.0
C
      RETURN
C
C END OF SUBROUTINE CELGAL
C
      END
