*DECK CHKDMY
C
C
C
      SUBROUTINE CHKDMY(ID,IM,IY,DATE,IDATE)
C
C THIS ROUTINE CHECKS THAT THE DAY, MONTH, AND YEAR, ID, IM, AND
C IY ARE WITHIN RANGE AND CONSISTENT.  IF SO DATE IS SET TO
C .TRUE. AND IDATE TO THE DATE AS YYMMDD.  OTHERWISE THESE VALUES
C ARE NOT CHANGED.
C
      DIMENSION NDAYS(12)
      LOGICAL DATE
      SAVE NDAYS
      DATA NDAYS/31,28,31,30,31,30,31,31,30,31,30,31/
C
C CHECK THE VALUES OF IY, IM, AND ID.
C
      IF(IY.GE.0.AND.IY.LE.99.AND.IM.GE.1.AND.IM.LE.12.AND.ID.GE.1) THEN
C
C THE BASIC VALUES ARE WITHIN RANGE, CHECK THE NUMBER OF DAYS.
C
        IF(ID.GT.NDAYS(IM)) THEN
C
C CHECK IF FEBRUARY AND A LEAP YEAR.
C
          IF(IM.EQ.2.AND.MOD(IY,4).EQ.0.AND.ID.EQ.29) THEN
C
C IT IS A VALID DATE, SET DATE.
C
            DATE=.TRUE.
            IDATE=IY*10000+IM*100+ID
          ENDIF
        ELSE
C
C IT IS A VALID DATE, SET DATE.
C
          DATE=.TRUE.
          IDATE=IY*10000+IM*100+ID
        ENDIF
      ENDIF
      RETURN
C
C END OF SUBROUTINE CHKDMY.
C
      END
