*DECK CPU
C
C
C
      CHARACTER*(*) FUNCTION CPU()
C
C THIS ROUTINE RETURNS THE NAME OF THE PROCESSOR WHICH IT IS RUNNING ON.
C THE NAME SHOULD NOT BE LONGER THAN 20 CHARACTERS.
C THIS ROUTINE IS INSTALLATION DEPENDENT.
C     VERSION 1.0   20MAY82        MANCHESTER STARLINK VAX 11/780
C
      CHARACTER NAME*(*)
      PARAMETER (NAME='M/C STARLINK VAX')
C
C RETURN THE NAME.
C
      CPU=NAME
      RETURN
C
C END OF CHARACTER*(*) FUNCTION NAME.
C
      END
