*DECK CTIMES
C
C
C
      CHARACTER*8 FUNCTION CTIMES(ITIME)
C
C RETURNS THE TIME ITIME AS INTEGER SECONDS INTO THE CHARACTER STRING
C CTIMES IN THE FORMAT HH:MM:SS.
C
      CHARACTER*8 CTIMEH
C
C FORM STRING.
C
      CTIMES=CTIMEH(ISTHMS(ITIME))
      RETURN
C
C END OF CHARACTER*8 FUNCTION CTIMES.
C
      END
