*DECK CTIMEH
C
C
C
      CHARACTER*8 FUNCTION CTIMEH(ITIME)
C
C RETURNS THE TIME ITIME AS AN INTEGER HHMMSS INTO THE CHARACTER STRING
C CTIMEH HH:MM:SS.
C
      CHARACTER BUFFER*8
C
C SPLIT ITIME INTO HH, MM AND SS.
C
      I=MOD(ABS(ITIME),240000)
      IHR=I/10000
      I=I-IHR*10000
      IMN=I/100
      ISC=I-IMN*100
      WRITE (BUFFER,100) IHR,IMN,ISC
      CTIMEH = BUFFER
      RETURN
C
C FORMAT.
C
  100 FORMAT (SS,I2.2,':',I2.2,':',I2.2)
C
C END OF CHARACTER*8 FUNCTION CTIMEH.
C
      END
