*DECK DROUND
C
C
C
      DOUBLE PRECISION FUNCTION DROUND(DVAL,NDEC)
C
C THIS ROUTINE RETURNS THE VALUE OF DVAL ROUNDED TO NDEC DECIMAL PLACES
C IN THE SAME WAY AS THE FORTRAN OUTPUT ROUTINES.  DVAL AND THE
C FUNCTION VALUE ARE BOTH DOUBLE PRECISION.
C
      CHARACTER BUFFER*30,FMT*8
      DOUBLE PRECISION DVAL,D
      SAVE FMT
      DATA FMT/'(F30.??)'/
C
C ADJUST THE FORMAT TO THE REQUESTED NUMBER OF DECIMAL PLACES.
C
      ND=MIN(27,MAX(0,NDEC))
      WRITE(FMT(6:7),800) ND
C
C WRITE DVAL INTO BUFFER WITH THIS NUMBER OF DECIMAL PLACES.
C
      WRITE(BUFFER,FMT,ERR=100,IOSTAT=I) DVAL
C
C WRITE SUCCESSFUL, SET DROUND TO THIS VALUE.
C
      READ(BUFFER,FMT,ERR=100,IOSTAT=I) D
      DROUND=D
      RETURN
C
C WRITE OR READ FAILED, RETURN AN ARITHMETICALLY ROUNDED VALUE.
C
  100 CONTINUE
      D=NINT(DVAL*10**ND)*10**(-ND)
      RETURN
C
C FORMAT STATEMENT.
C
  800 FORMAT(I2)
C
C END OF DOUBLE PRECISION FUNCTION DROUND.
C
      END
