*DECK ERRSCA
C
C **************************************************************
      FUNCTION ERRSCA ( CVAL, CERR )
C **************************************************************
C
C EXAMINES THE CHARACTER STRINGS FOR A VALUE ( CVAL ) AND ITS ERROR
C     ( CERR ). IF CERR HAS NO DECIMAL POINT, THEN IT IS ASSUMED TO
C     REFER TO THE LAST PLACES OF THE VALUE, AND THE ROUTINE RETURNS
C     THE SCALING REQUIRED TO CONVERT THE ERROR TO ITS ACTUAL VALUE.
C
C E.G. CVAL = '1.23' AND CERR = '4' WILL RETURN ERRSCA = 0.01
C     ENABLING 1.23 +- 4 TO BE CORRECTLY INTERPRETED AS BEING
C     EQUIVALENT TO 1.23 +- 0.04
C
      CHARACTER*(*) CVAL,CERR
C
C     DEFAULT SCALING IS UNITY.
C
      ERRSCA = 1.0
C
C     RETURN IF EITHER INPUT STRING IS EMPTY.
C
      IF ( CVAL.EQ.' '.OR.CERR.EQ.' ' ) RETURN
C
C     RETURN IF THERE IS A DECIMAL POINT IN THE ERROR STRING.
C
      IF ( INDEX(CERR,'.').NE.0 ) RETURN
C
C     SET THE SCALE FROM THE NUMBER OF DECIMAL PLACES
C     IN THE VALUE STRING.
C
      ERRSCA = 10.0**(LENGTH(CVAL)-INDEX(CVAL,'.'))
C
      RETURN
C
C END OF FUNCTION ERRSCA
C
      END
