      SUBROUTINE GETIOMSG(ERRMESS,L)
C RETURNS THE MOST RECENT IO ERROR MESSAGE
      CHARACTER ERRMESS*(*)
      INTEGER L

      INTEGER FNUM, STATUS, STATV, LUNIT, CONDVAL
      CALL ERRSNS (FNUM, STATUS, STATV, LUNIT, CONDVAL)
      CALL SYS$GETMSG (%VAL (STATUS), L, ERRMESS,,)
      END
