*DECK GETLIN
C
C
C
      SUBROUTINE GETLIN(IUNIT,ISTAT,LENPAG,LENLIN,NUMPAG,NUMLIN,IFAIL)
C
C RETURN STATUS OF AN OUTPUT UNIT.
C
C FIRST SEARCH FOR THE UNIT.
C
      CALL OUTSER(ICHAN,IUNIT)
C
C UNIT NOT SET UP.
C
      IF(ICHAN.EQ.0) THEN
        CALL LIBERR('GETLIN',33,0,IUNIT,0.0,' ',IFAIL)
        RETURN
      ENDIF
C
C GET PARAMETERS AND RETURN.
C
      CALL OUTGET(ICHAN,ISTAT,IFAIL,LENPAG,LENLIN,NUMPAG,NUMLIN)
      IFAIL=0
      RETURN
C
C END OF SUBROUTINE GETLIN.
C
      END
