*DECK HLPCMD
C
C
C **************************************************************
      SUBROUTINE HLPCMD ( CMDINP, NINP, IDENT, IFAIL )
C **************************************************************
C
C PROCESSES THE HELP COMMAND.
C HELP IS PROVIDED FOR PROGRAM IDENT FOR THE SUBJECTS CONTAINED
C    IN CMDINP(NINP).
C IFAIL IS ZERO UNLESS AN ERROR OCCURRED
C
C THIS ROUTINE IS INSTALLATION DEPENDENT
C
C VAX-11 FORTRAN VERSION
C
      CHARACTER CMDINP(*)*(*),IDENT*(*),OUTBUF*81,HLPFIL*40
      LOGICAL BATCH
      DATA HLPFIL / 'PSRHELPDIR:PSR' /
C
C     CLEAR THE ERROR FLAG
C
      IFAIL = 0
C
C TEST IF IN BATCH MODE.
C
      IF(BATCH()) THEN
C
C HELP NOT SUPPORTED IN BATCH MODE.
C
         CALL PSRERR ('HLPCMD',35,0,0.0,'The HELP command is',IFAIL)
      ELSE
C
C PRINT THE REQUIRED HELP INFORMATION.  FIRST PACK THE PROGRAM NAME
C FOLLOWED BY THE COMMAND PARAMETERS INTO OUTBUF.
C
        LO=LEN(OUTBUF)
        IC=LENGTH(IDENT)+1
        OUTBUF=IDENT
        DO 1 I=2,NINP
C
C TEST IF THERE IS ROOM FOR THE CURRENT PARAMETER.
C
          LP=LENGTH(CMDINP(I))
          IF(IC+LP.GT.LO) THEN
C
C NO MORE ROOM, MONITOR AN ERROR AND RETURN.
C
            CALL PSRERR ('HLPCMD',14,0,0.0,' ',IFAIL)
            RETURN
          ENDIF
C
C THERE IS ROOM, LOAD IT INTO OUTBUF.
C
          OUTBUF(IC+1:IC+LP)=CMDINP(I)(1:LP)
C
C ADJUST THE CHARACTER POINTER.
C
          IC=IC+LP+1
    1   CONTINUE
C
C NOW PRINT THE HELP INFORMATION.
C
c        ISTAT=LBR$OUTPUT_HELP(LIB$PUT_OUTPUT,80,OUTBUF,HLPFIL,,
c     &  LIB$GET_INPUT)
C
C TEST IF SUCESSFUL.
C
c        IF(ISTAT) THEN
C
C YES, CLEAR IFAIL.
C
          IFAIL=0
c        ELSE
C
C NO, SET IFAIL.
C
c          IFAIL=3
c        ENDIF
      ENDIF
C
      RETURN
C
C END OF SUBROUTINE HLPCMD
C
      END





