*DECK ISTHMS
C
C
C
      FUNCTION ISTHMS(ITIME)
C
C TURNS THE INTEGER TIME ITIME FROM SECONDS INTO INTEGER HHMMSS.
C
C EVALUATE ISTHMS.
C
      I=MOD(ITIME,86400)
      J=I/3600
      K=(I-J*3600)/60
      ISTHMS=6400*J+40*K+I
      RETURN
C
C END OF INTEGER FUNCTION ISTHMS.
C
      END
