*DECK LITDEL
C
C
C
      CHARACTER*(*) FUNCTION LITDEL()
C
C THIS ROUTINE RETURNS THE LITERAL DELIMITER CHARACTER USED TO DISABLE
C CASE CONVERSION IN GETCMD.
C     VERSION 1.0   19NOV82
C
      CHARACTER DEL*(*)
      PARAMETER (DEL='"')
C
C RETURN THE DELIMITER.
C
      LITDEL=DEL
      RETURN
C
C END OF CHARACTER*(*) FUNCTION LITDEL.
C
      END
