*DECK OCESET
C
C **************************************************************
      SUBROUTINE OCESET ( ERRLOG )
C **************************************************************
C
C SETS THE ERROR STATUS FOR OUTPUT CONVERSION ERROR ( OCE ).
C IF ERRLOG IS .TRUE. AN ERROR IS REPORTED,
C OTHERWISE NO ERROR IS PRODUCED.
C
C
C THIS ROUTINE IS INSTALLATION DEPENDENT
C
C SUN FORTRAN VERSION (DUMMY ROUTINE)
C
      LOGICAL ERRLOG
C
C     SET THE ERROR STATUS
C
c      CALL ERRSET (63,.NOT.ERRLOG,ERRLOG,ERRLOG,ERRLOG,)
C 
      RETURN
C
C END OF SUBROUTINE OCESET
C
      END
