*DECK OPSTAT
C
C
C
      SUBROUTINE OPSTAT(IUNIT,ISTAT,IFAIL)
C
C SWITCH STATUS OF AN OUTPUT CHANNEL.
C
C FIRST SEARCH FOR SPECIFIED CHANNEL.
C
      CALL OUTSER(ICHAN,IUNIT)
C
C CHANNEL NOT SET UP.
C
      IF(ICHAN.EQ.0) THEN
        CALL LIBERR('OPSTAT',33,0,IUNIT,0.0,' ',IFAIL)
        RETURN
      ENDIF
C
C SET UP STATUS AND RETURN.
C
      CALL OUTSTA(ICHAN,ISTAT)
      IFAIL=0
      RETURN
C
C END OF SUBROUTINE OPSTAT.
C
      END
