*DECK PARINT
C
C
C
      LOGICAL FUNCTION PARINT(PAR,IVAL)
C
C ATTEMPTS TO INTERPRET THE PARAMETER STRING PAR AS AN INTEGER.  RETURNS
C THE VALUE .TRUE. IF SUCCESSFUL AND .FALSE. OTHERWISE.  ON EXIT IVAL
C CONTAINS THE INTEGER VALUE IF PARINT IS .TRUE. AND IS UNCHANGED OTHERWISE.
C
      CHARACTER PAR*(*),FMT*8
C
C SET UP THE INITIAL VALUES.
C
      PARINT=.FALSE.
C
C SCAN THROUGH PAR TO LOCATE THE FIRST NON-SPACE CHARACTER.
C
      LP=LENGTH(PAR)
      DO 1 I=1,LP
        IF(PAR(I:I).NE.' ') GOTO 1000
    1 CONTINUE
      RETURN
C
C EVALUATE THE NUMBER OF CHARACTERS IN THE PARAMETER.
C
 1000 NC=LP-I+1
C
C FRIG THE FORMAT STATEMENT TO GIVE THIS FIELD SIZE.
C
      WRITE(FMT,800) NC
C
C NOW ATTEMPT TO READ THE PARAMETER AS AN INTEGER.
C
      READ(PAR(I:LP),FMT,ERR=100,IOSTAT=NC) I
      IF(ABS(I).LE.MAXINT()) THEN
C
C READ SUCCESSFUL.
C
        PARINT=.TRUE.
        IVAL=I
      ENDIF
      RETURN
C
C READ UNSUCCESSFUL.
C
  100 CONTINUE
      RETURN
C
C FORMAT STATEMENT.
C
  800 FORMAT(SS,'(BN,I',I2,')')
C
C END OF LOGICAL FUNCTION PARINT.
C
      END
