*DECK PARSE
C
C *********************************************************************
      SUBROUTINE PARSE ( STRING, PARS, NPAR, MAXPAR, DELIM )
C *********************************************************************
C
C SPLITS THE CHARACTER ARRAY STRING INTO PARAMETERS SEPARATED BY
C    THE DELIMITERS DELIM
C THE NTH CHARACTER OF DELIM IS USED TO TERMINATE THE NTH
C PARAMETER, THE FINAL CHARACTER BEING REPEATED IF NECESSARY
C THE PARAMETERS ARE RETURNED IN PARS(MAXPAR) AND THEIR NUMBER IS NPAR
C
      CHARACTER*(*) STRING,PARS(MAXPAR),DELIM
C
C L HOLDS THE POSITION OF THE LAST DELIMITER FOUND
C IDEL POINTS TO THE CURRENT DELIMITER CHARACTER
C
      LENDEL = LEN(DELIM)
      IDEL = 1
      NPAR=0
      L=0
      DO 10 I=1,LENGTH(STRING)
         IF ( STRING(I:I).EQ.DELIM(IDEL:IDEL) ) THEN
            IF ( I-L.GT.1 ) THEN
C
C              NON-ZERO LENGTH STRING BETWEEN DELIMITERS FOUND
C              CHECK NUMBER OF PARAMETERS AGAINST MAXPAR
C              STORE CURRENT PARAMETER
C              UPDATE DELIMITER CHARACTER
C
               IF ( NPAR+1.GT.MAXPAR ) GOTO 100
               NPAR = NPAR+1
               PARS(NPAR) = STRING(L+1:I-1)
               IDEL = MIN(IDEL+1,LENDEL)
            ENDIF
            L=I
         ENDIF
   10 CONTINUE
C
C     IF A STRING IS REMAINING AT THE END, ADD IT TO PARS
C
      IF ( L.LT.LEN(STRING) ) THEN
         IF ( NPAR+1.GT.MAXPAR ) GOTO 100
         NPAR = NPAR+1
         PARS(NPAR) = STRING(L+1:LEN(STRING))
      ENDIF
C
  100 CONTINUE
      RETURN
C
C END OF SUBROUTINE PARSE
C
      END




