*DECK PARTIM
C
C
C
      LOGICAL FUNCTION PARTIM(PAR,TIME)
C
C TRIES TO INTERPRET THE PARAMETER STRING PAR AS A TIME.  RETURNS THE
C VALUE .TRUE. IF SUCCESSFUL AND .FALSE. OTHERWISE.  ON EXIT TIME CONTAINS
C THE TIME IN SECONDS IF PARTIM IS .TRUE. AND IS UNCHANGED OTHERWISE.
C
      CHARACTER PAR*(*),STR(2)*2
      LOGICAL PARDBL
      DOUBLE PRECISION TIME,SECS
C
C SET UP THE INITIAL VALUES.
C
      PARTIM=.FALSE.
      if (par(1:).eq.'<') return
      DO 1 I=1,2
    1 STR(I)=' '
      J=1
      IC=0
C
C SCAN THROUGH PAR AND ATTEMPT TO LOAD STR WITH ITS COMPONENT BITS.
C
      LP = LENGTH(PAR)
      DO 2 I=1,LP
        IF(PAR(I:I).EQ.':') THEN
C
C COLON, INCREMENT THE HMS POINTER.
C
          J=J+1
          IF(J.GT.2) THEN
C
C START OF THE SECONDS PART.
C
            GOTO 1001
          ENDIF
C
C CLEAR THE CHARACTER COUNTER.
C
          IC=0
        ELSEIF(PAR(I:I).NE.' ') THEN
C
C CHARACTER OTHER THAN SPACE, LOAD INTO STR.
C
          IC=IC+1
          IF(IC.GT.2) THEN
C
C STRING TOO LONG, NOT A TIME.
C
            RETURN
          ENDIF
C
C LOAD INTO STR.
C
          STR(J)(IC:IC)=PAR(I:I)
        ENDIF
    2 CONTINUE
C
C NOW ATTEMPT TO READ THE SECONDS PART AS A REAL NUMBER.
C
 1001 IF (I.GE.LP) THEN
C
C NO SECONDS SUPPLIED.
C
        SECS=0.0
      ELSEIF (.NOT.PARDBL(PAR(I+1:),SECS)) THEN
C
C NOT A REAL NUMBER.
C
        RETURN
      ENDIF
C
C CHECK THE SIGN AND MAGNITUDE OF SECS.
C
      IF ( SECS.LT.0.0.OR.SECS.GT.60.0 ) RETURN
C
C NOW ATTEMPT TO READ STR AS INTEGERS.  EXIT TO 1000 IF THE READ FAILS.
C
      IF(J.NE.1) THEN
        READ(STR,800,ERR=1000) I,J
C
C CHECK THE HM IN I AND J.
C
        IF(J.LT.0.OR.J.GT.59) RETURN
        IF(I.LT.0.OR.I.GT.24
     &     .OR.I.EQ.24.AND.(J.NE.0.OR.SECS.NE.0.0)) RETURN
C
C STRING IS A TIME, RETURN AS SECONDS.
C
        TIME=3600*I+60*J+SECS
        PARTIM=.TRUE.
      ENDIF
 1000 RETURN
C
C FORMAT STATEMENT.
C
  800 FORMAT(BN,2(I2:/))
C
C END OF LOGICAL FUNCTION PARTIM.
C
      END
