*DECK RDBLOCK
C
C ***********************************************************
      LOGICAL FUNCTION RDBLOCK ( LU,IFAIL )
C ***********************************************************
C
C     READS CHARACTER DATA FROM UNIT LU AND INTERPRETS
C     IT AS PULSAR DATA IN MAGNETIC TAPE FORMAT RETURNING THE
C     HEADER AND DATA OF THE NEXT DATA BLOCK IN THE ARRAYS
C     DECLARED IN 'PSRDAT.DEF'.
C     THE FUNCTION IS .TRUE. UNLESS END-OF-FILE IS ENCOUNTERED
C     OR THERE IS AN ERROR.
C     IFAIL=0 UNLESS THERE IS AN ERROR.
C

      INCLUDE 'PSRDAT.DEF'
      LOGICAL RDHEAD
C
C     CLEAR SUCCESS FLAG.
C
      RDBLOCK = .FALSE.
C
C     READ A HEADER.
C
      IF ( RDHEAD(LU,IFAIL) ) THEN
C
C        PERFORM PRE-EDITTING.
C
         CALL EDIT ( EDTLST,NEDT,MAXEDP,-1,IFAIL )
         IF ( IFAIL.NE.0 ) RETURN
C
C        READ THE DATA, CLEARING THE WRITE POINTER FIRST.
C
         INWR = 0
         CALL RDDAT (IFAIL)
         IF ( IFAIL.NE.0 ) RETURN
C
C        PERFORM ANY POST-EDITTING.
C
         CALL EDIT ( EDTLST,NEDT,MAXEDP,+1,IFAIL )
         IF ( IFAIL.NE.0 ) RETURN
      ELSE
         RETURN
      ENDIF
C
C     FLAG SUCCESS.
C
      RDBLOCK = .TRUE.
      RETURN
C
C END OF LOGICAL FUNCTION RDBLOCK.
C
      END
