*DECK ROUNDN
C
C
C
      FUNCTION ROUNDN(RVAL,NDEC)
C
C THIS ROUTINE RETURNS THE VALUE OF RVAL ROUNDED TO NDEC DECIMAL PLACES
C IN THE SAME WAY AS THE FORTRAN OUTPUT ROUTINES.
C
      CHARACTER BUFFER*30,FMT*8
      SAVE FMT
      DATA FMT/'(F30.??)'/
C
C ADJUST THE FORMAT TO THE REQUESTED NUMBER OF DECIMAL PLACES.
C
      ND=MIN(27,MAX(0,NDEC))
      WRITE(FMT(6:7),800) ND
C
C WRITE RVAL INTO BUFFER WITH THIS NUMBER OF DECIMAL PLACES.
C
      WRITE(BUFFER,FMT,ERR=100,IOSTAT=I) RVAL
C
C WRITE SUCCESSFUL, SET ROUNDN TO THIS VALUE.
C
      READ(BUFFER,FMT,ERR=100,IOSTAT=I) R
      ROUNDN=R
      RETURN
C
C WRITE OR READ FAILED, RETURN AN ARITHMETICALLY ROUNDED VALUE.
C
  100 CONTINUE
      R=NINT(RVAL*10**ND)*10**(-ND)
      RETURN
C
C FORMAT STATEMENT.
C
  800 FORMAT(I2)
C
C END OF REAL FUNCTION ROUNDN.
C
      END
