*DECK SHOOBE
C
C
C
      SUBROUTINE SHOOBE(BUFFER,IUPTR,IUNIT)
C
C THIS ROUTINE PRINTS OUT THE CURRENT OBEY FILE.
C INPUT ARGUMENTS:
C  BUFFER   - A CHARACTER BUFFER TO HOLD THE OUTPUT LINE.
C  IUPTR    - THE CURRENT GETCMD UNIT POINTER.
C  IUNIT    - THE LIST OF AVAILABLE UNITS.
C     VERSION 1.0   17MAY85
C
      CHARACTER BUFFER*(*)
      DIMENSION IUNIT(*)
C
C LOAD THE INITIAL TEXT.
C
      BUFFER='   Current command file:'
C
C TEST IF THERE IS AN OBEY FILE OPEN.
C
      IF(IUPTR.GT.1) THEN
C
C YES, OBTAIN ITS NAME.
C
        INQUIRE(IUNIT(IUPTR),NAME=BUFFER(LENGTH(BUFFER)+2:))
      ELSE
C
C NO, PRINT <default>.
C
        BUFFER(LENGTH(BUFFER)+2:)='<default>'
      ENDIF
C
C PRINT THE LINE.
C
      CALL OUTLIN(BUFFER,1)
      RETURN
C
C END OF SUBROUTINE SHOOBE.
C
      END
