*DECK SHOSAV
C
C
C
      SUBROUTINE SHOSAV(BUFFER,ISAVE,NUNITS,IUNIT)
C
C THIS ROUTINE PRINTS THE CURRENT SAVE FILE NAME.
C INPUT ARGUMENTS:
C  BUFFER   - A CHARACTER BUFFER WHICH CAN HOLD A COMMAND LINE.
C  ISAVE    - 0 IF NO SAVE FILE IS OPEN, ELSE > 0.
C  NUNITS   - THE NUMBER OF UNITS AVAILABLE (= SAVE FILE UNIT IN IUNIT).
C  IUNIT    - THE GETCMD UNITS ARRAY.
C     VERSION 1.0   17MAY85
C
      CHARACTER BUFFER*(*)
      DIMENSION IUNIT(*)
C
C LOAD THE TEXT INTO THE OUTPUT BUFFER.
C
      BUFFER='   Current save file:'
C
C NOW TEST IF THERE IS A SAVE FILE OPEN.
C
      IF(ISAVE.GT.0) THEN
C
C YES, OBTAIN ITS NAME.
C
        INQUIRE(IUNIT(NUNITS),NAME=BUFFER(LENGTH(BUFFER)+2:))
      ELSE
C
C NO, PRINT < none>.
C
        BUFFER(LENGTH(BUFFER)+2:)='<none>'
      ENDIF
C
C PRINT THE LINE.
C
      CALL OUTLIN(BUFFER,1)
      RETURN
C
C END OF SUBROUTINE SHOSAV.
C
      END
