*DECK SUPCHR
C
C
C
      CHARACTER*(*) FUNCTION SUPCHR()
C
C THIS ROUTINE RETURNS THE CHARACTER THAT IS USED AT THE START OF A
C PARAMETER TO SUPPRESS SYMBOL SUBSTITUTION FOR IT.
C     VERSION 1.0   15MAY85
C
      CHARACTER*(*) SCHAR
      PARAMETER (SCHAR='_')
C
C RETURN THE CHARACTER.
C
      SUPCHR=SCHAR
      RETURN
C
C END OF CHARACTER*(*) FUNCTION SUPCHR.
C
      END
