*DECK UNSAST
C***********************************************************************
      INTEGER FUNCTION UNSAST(CHAN)
C***********************************************************************
C
C AST ROUTINE ON CTRL Y/C TO PUT UP A FLAG FOR HIGHER LEVEL ROUTINES.
C TO USE THE FACILITY IN A SUBROUTINE THE FOLLOWING COMMON DECLARATION 
C   MUST BE MADE.  UPON ENTRY TO SUCH A SUBROUTINE, THE OLAF ROUTINE 
C   "UNSAFE" MUST BE CALLED.   CNTRLYC WILL BECOME TRUE IF CNTRL Y OR
C   CNTRL C IS DEPRESSED AND MAY BE INSPECTED AT ANY TIME.  A CALL TO 
C   THE OLAF ROUTINE "SAFE" MUST BE MADE BEFORE RETURNING FROM THE 
C   SUBROUTINE.
C
      COMMON/CNTRLYC/CNTRLYC
      LOGICAL CNTRLYC
C
      INTEGER CHAN
C
      CNTRLYC=.TRUE.
      UNSAST=1
      END
