*DECK USRLER
C
C
C
      SUBROUTINE USRLER(ROUTN,IERR)
C
C DUMMY ROUTINE CAN BE PROVIDED BY USER. CALLED BY LIBERR ON FATAL
C ERRORS.
C VERRSION 1.1   21OCT81
C
      CHARACTER*(*) ROUTN
      RETURN
C
C END OF SUBROUTINE USRLER.
C
      END
