

      PROGRAM SQUASHPLOT
      INTEGER DATEMIN,DATEMAX,PARDATE,ERROR1
      REAL RES,SUBVALUE,NEWRES
      CHARACTER LINEA*37,FILENAM*15,FILENAM2*20,LINEB*47

      WRITE(*,'(''ENTER NAME OF FILE TO BE CHANGED: '',$)')
      READ(*,'(A)')FILENAM
      WRITE(*,'(''ENTER NAME OF FILE TO BE WRITTEN: '',$)')
      READ(*,'(A)')FILENAM2
      WRITE(*,*)FILENAM
      WRITE(*,'(''DATE FROM WHICH CHANGE REQUIRED: '',$)')
      READ(*,'(I5)')DATEMIN
      WRITE(*,'(''DATE TO WHICH CHANGE REQUIRED: '',$)')
      READ(*,'(I5)')DATEMAX
      WRITE(*,'(''AMOUNT TO BE SUBTRACTED: '',$)')
      READ(*,'(F8.3)')SUBVALUE

      OPEN(UNIT=10,FILE=FILENAM,STATUS='OLD',FORM='FORMATTED')
      OPEN(UNIT=20,FILE=FILENAM2,STATUS='NEW',FORM='FORMATTED')

 1000 READ(10,'(2X,I5,A37,F9.6,A47)',END=3000,IOSTAT=ERROR1)PARDATE,
     /  LINEA,RES,LINEB
      IF (ERROR1 .NE. 0) THEN
        WRITE(*,*) 'ERROR READING PARAMETERS, ERROR1= ',ERROR1
        WRITE(*,*)PARDATE
        GOTO 1000
      ELSEIF (PARDATE .LT. DATEMIN .OR. PARDATE .GT. DATEMAX) THEN
        WRITE(20,'(2X,I5,A37,F9.6,A47)')PARDATE,LINEA,RES,LINEB
        GOTO 1000
      ELSE
        NEWRES=RES+SUBVALUE
        WRITE(20,'(2X,I5,A37,F9.6,A47)')PARDATE,LINEA,NEWRES,LINEB
        GOTO 1000
      ENDIF

 3000 CLOSE(10)
      CLOSE(20)
      WRITE(*,*)'FILE ',FILENAM2,'WRITTEN '
      END
