

      PROGRAM SQUASHPLOTB
      INTEGER DATEMIN,DATEMAX,PARDATE,ERROR1
      REAL SUBVALUE
      DOUBLE PRECISION PER,NEWPER
      CHARACTER LINE1*78,LINEA*9,FILENAM*15,FILENAM2*20,LINEB*50

      WRITE(*,'(''ENTER NAME OF FILE TO BE CHANGED: '',$)')
      READ(*,'(A)')FILENAM
      WRITE(*,'(''ENTER NAME OF FILE TO BE WRITTEN: '',$)')
      READ(*,'(A)')FILENAM2
      WRITE(*,*)FILENAM
      WRITE(*,'(''DATE FROM WHICH CHANGE REQUIRED: '',$)')
      READ(*,'(I5)')DATEMIN
      WRITE(*,'(''DATE TO WHICH CHANGE REQUIRED: '',$)')
      READ(*,'(I5)')DATEMAX
      WRITE(*,'(''AMOUNT TO BE SUBTRACTED: '',$)')
      READ(*,'(F8.3)')SUBVALUE

      OPEN(UNIT=10,FILE=FILENAM,STATUS='OLD',FORM='FORMATTED')
      OPEN(UNIT=20,FILE=FILENAM2,STATUS='NEW',FORM='FORMATTED')

      READ(10,'(A78)')LINE1
      WRITE(20,'(A78)')LINE1
 1000 READ(10,'(1X,I5,A9,F13.9,A50)',END=3000,IOSTAT=ERROR1)PARDATE,
     /  LINEA,PER,LINEB
      IF (ERROR1 .NE. 0) THEN
        WRITE(*,*) 'ERROR READING PARAMETERS, ERROR1= ',ERROR1
        WRITE(*,*)PARDATE
        GOTO 1000
      ELSEIF (PARDATE .LT. DATEMIN .OR. PARDATE .GT. DATEMAX) THEN
        WRITE(20,'(1X,I5,A9,F13.9,A50)')PARDATE,LINEA,PER,LINEB
        GOTO 1000
      ELSE
        NEWPER=PER+SUBVALUE
        WRITE(20,'(1X,I5,A9,F13.9,A50)')PARDATE,LINEA,NEWPER,LINEB
        GOTO 1000
      ENDIF

 3000 CLOSE(10)
      CLOSE(20)
      WRITE(*,*)'FILE ',FILENAM2,'WRITTEN '
      END





